name: Deploy AWS VPC

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - '**.tf'           
      - '**.tfvars'       
      - '.github/workflows/**' 

permissions:
  id-token: write
  contents: read

jobs:
  deploy-vpc:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Init
        run: terraform init -migrate-state
        working-directory: . 

      - name: Terraform Validate
        run: terraform validate
        working-directory: . 

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -out=tfplan
        working-directory: . 

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: . 

      - name: Terraform Output
        id: output
        run: |
          # get the json format output
          echo "vpc_info=$(terraform output -json vpc_configurations)" >> $GITHUB_OUTPUT
        working-directory: .

      - name: Display outputs
        run: |
          echo "✅ VPCs Successfully Created/Updated!"
          echo "Full Configs: ${{ steps.output.outputs.vpc_info }}"